### ISSUE TITLE
is this the unsupervised learning?

### ISSUE THREAD

**Issue by robinzixuan** [fireindark707/Python-Schema-Matching#1]
is this unsupervised learning?

**Comment by fireindark707** [comment]
No, You need to provide annotated table pairs. I have provided some as examples

**Comment by robinzixuan** [comment]
Thanks

**Comment by robinzixuan** [comment]
I believe your method is interesting and helpful for our project. whether you consider any unsupervised methods for that? Also, whether you already have some published paper for this repo can provide

**Comment by fireindark707** [comment]
> I believe your method is interesting and helpful for our project. whether you consider any unsupervised methods for that? Also, whether you already have some published paper for this repo can provide

No, I did not publish a paper based on this, but if you are interested, feel free to quote this repo. Glad it can be of some help. I have the impression that some researchers used clustering methods, but their results were limited. So I did not consider unsupervised methods.

**Comment by robinzixuan** [comment]
I redesigned your work with LightGBM and found the result is not bad. It is workable in the open domain. I just wonder whether you have an interest on punished a paper based on that. I would like to contribute to that. If you are interested, you can contact me with my email, luohaozh@gmail.com

**Comment by fireindark707** [comment]
@robinzixuan Great! I have sent the mail
