### ISSUE TITLE
Training and Testing the schema-matching scripts

### ISSUE THREAD

**Issue by sagargowda88** [fireindark707/Python-Schema-Matching#4]
Hi 
Can you share the detailed steps on how to train and test the xgboost model. the code is asking for "Input" folder. what all things show i put in input folder to train and test?

**Comment by fireindark707** [comment]
Hi, @sagargowda88 
You don't need to put anything in "Input" folder. You need to run 

`
python relation_features.py
`

This script will create the features from train folder and create input folder.

**Comment by sagargowda88** [comment]
Hi @fireindark707,

Thanks for your response. I tried it worked. Also when there is only one pair in Training Data Folder and i run relation_features.py, only test folder .npy files get created and train folder is empty (in Input folder). 

![image](https://github.com/fireindark707/Python-Schema-Matching/assets/46260031/f726e75f-f836-46a9-abc8-6d37d091127f)

Also when i keep 2 pairs in Training Data Folder and run relation_features.py, the Input folder gets created but train and test .npy files gets interchanged as shown below:
![image](https://github.com/fireindark707/Python-Schema-Matching/assets/46260031/929555ef-14f4-4160-ad12-c888acb9c14d)

**Comment by sagargowda88** [comment]
it worked. Thanks
